apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minipj-ingress
  namespace: miniproject
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80
