---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  selector:
    app: jenkins-server
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      # nodePort: 32000
    - name: jnlp
      port: 50000
      targetPort: 50000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-jnlp
#   namespace: jenkins
# spec:
#   type: LoadBalancer
#   ports:

#   selector:
#     app: jenkins-server
