---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    kubernetes.digitalocean.com/load-balancer-id: "cb24d630-daaa-459e-a140-a1893b0fb132"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "2"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
spec:
  selector:
    app: jenkins-server
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080

      # nodePort: 32000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: jenkins
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins-server
